# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_creater', '0002_auto_20161004_1851'),
    ]

    operations = [
    ]
