# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 20:23
from __future__ import unicode_literals

from django.db import migrations

import csv


def add_Fighter_data(apps, schema_editor):
    Fighter = apps.get_model("table_creater", "Fighter")
    with open('ufc.csv') as infile:
        reader = csv.DictReader(infile, fieldnames=["rank", "last_name", "first_name", "fights",
                                "strikes", "str_accuracy", "takedowns", "td_accuracy",
                                                    "knockdowns", "passes", "reversals", "submissions"])
        for row in reader:
            Fighter.objects.create(rank=row["rank"], last_name=row["last_name"],
                                   first_name=row["first_name"], fights=row["fights"], strikes=row["strikes"],
                                   str_accuracy=row["str_accuracy"], takedowns=row["takedowns"],
                                   td_accuracy=row["td_accuracy"], knockdowns=row["knockdowns"],
                                   reversals=row["reversals"], passes=row["passes"], submissions=row["submissions"])


class Migration(migrations.Migration):

    dependencies = [
        ('table_creater', '0004_auto_20161004_1940'),
    ]

    operations = [
        migrations.RunPython(add_Fighter_data)
    ]
